version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      - npm i
  build:
    commands:
      - LOCAL_PORT=8080
      - DOCKER_PORT=80
      - DOCKER_TAG=local_dev/app_name
      - DOCKER_DEBUG=''
      - npm run build --silent
artifacts:
  files:
    - '**/*'
